name: shop_cfast
description: Cfast classifieds Ads.
publish_to: 'none' 
version: 1.0.8+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.7
  http: ^1.1.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  iconly:
  pin_code_fields:
  dotted_border:
  ionicons: ^0.2.2
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  flutter_staggered_grid_view: ^0.4.0
  google_mobile_ads: ^3.1.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.6
  image_picker: ^0.8.4+4
  image_watermark: ^0.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^9.0.0
  #share: ^2.0.4
  share_plus: ^7.2.2
  provider: ^6.0.1
  badges: ^3.1.2
  webview_flutter: ^4.0.5
  image: ^3.0.1
  connectivity_plus: 2.3.0
  get: ^4.6.5
  change_app_package_name: ^1.0.0
  firebase_core: ^2.20.1
  firebase_core_web: ^2.7.0
  firebase_messaging: ^14.7.0
  firebase_messaging_web: ^3.5.0
  firebase_crashlytics: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
